baseURL = 'https://blog.zbw.uk/'
defaultContentLanguage = "zh-hans"
title = '博客于文'
theme = 'PaperMod'
hasCJKLanguage = true
summaryLength = 10

[pagination]
  pagerSize = 10

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  author = 'Bowen Zhang'
  description = '博学于文，约之以礼 | B.S. at CUFE 27'
  defaultTheme = 'auto'          # auto / light / dark
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true

  # Profile 模式主页
  [params.profileMode]
    enabled = true
    title = 'Bowen Zhang'
    subtitle = '博学于文，约之以礼
    imageUrl = 'images/avatar.svg'
    imageWidth = 120
    imageHeight = 120
    imageTitle = '张博文'

    [[params.profileMode.buttons]]
      name = '个人主页'
      url = 'https://zbw.uk'

  # 社交图标
  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/MuonChaser'

  [[params.socialIcons]]
    name = 'email'
    url = 'mailto:zbw.init@gmail.com'

  [[params.socialIcons]]
    name = 'linkedin'
    url = 'https://www.linkedin.com/in/zhangbowen'

  [[params.socialIcons]]
    name = 'rss'
    url = '/index.xml'

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = '文章'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'categories'
    name = '分类'
    url = '/categories/'
    weight = 20
  [[menu.main]]
    identifier = 'tags'
    name = '标签'
    url = '/tags/'
    weight = 30
  [[menu.main]]
    identifier = 'archives'
    name = '归档'
    url = '/archives/'
    weight = 35
  [[menu.main]]
    identifier = 'search'
    name = '搜索'
    url = '/search/'
    weight = 40

[outputs]
  home = ['HTML', 'RSS', 'JSON']
