baseURL = 'http://blog.bwzhang.cn/'
defaultContentLanguage = "zh-hans"
title = '博客于文'
theme = 'maupassant'
hasCJKLanguage = true
summaryLength = 10

# 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
toc = true  # 是否开启目录
# 是否启用自动折叠侧边栏（默认为 false）
autoSidebarCollapse = false
[author]
  name = 'Bowen Zhang'

[params]
  author = 'Bowen Zhang'
  subtitle = '博学于文，约之以礼'
  description = 'B.S. at CUFE 27'
  customCSS = ['style.css']


