baseURL = 'http://localhost:1313/'
languageCode = "zh-CN"
title = '博客于文'
theme = 'maupassant'
hasCJKLanguage = true
summaryLength = 10

[author]
  name = 'Bowen Zhang'

[params]
  author = 'Bowen Zhang'
  customCSS = ['style.css']
